export const SCREENS = {
    INTRO: 'INTRO',
    REG_1: 'REG_1',
    REG_2: 'REG_2',
    VIP_START: 'VIPSTART',
    LOGIN: 'LOGIN',
    LOBBY: 'LOBBY',
    START: 'START',
    START2: 'START2',
    GAME1: 'GAME1',
    GAME2: 'GAME2',
    GAME3: 'GAME3',
    GAME4: 'GAME4',
    FINISH: 'FINISH',
}

export const NEXT_SCREENS = {
    [SCREENS.REG_1]: SCREENS.REG_2,
    [SCREENS.REG_2]: SCREENS.START,
    [SCREENS.START]: SCREENS.START2,
    [SCREENS.START2]: SCREENS.LOBBY,
}
